# THEME_COLOR = "#375362"
THEME_COLOR = "#50BAA0"
PADDING = 20
WINDOW_HEIGHT = 10
WINDOW_WIDTH = 20
FONT = "Arial"
FONT_SIZE = 15
FONT_SIZE_L =25
SM_FONT_SIZE = 10
LABEL_FONT_SIZE = 15
FONT_STYLE = "bold"
WHITE = "white"
BTN_COLOR="#FA7B52"

LEFT='w'
RIGHT = "e"
WINDOW_SIZE = "600x400"
WINDOW_SIZE_L = "800x400"


#home buttons
HOME_BTN_HEIGHT = 5
HOME_BTN_WIDTH  = 8
HOME_BTN_FONT_SIZE = 10
HOME_BTN_COLOR = '#eab676'

#VAULT BTN WIDTH
VAULT_BTN_WIDTH = 12

#LOGIN PAGE
EMAIL_ENTRY_WIDTH = 35
KEY_ENTRY_WIDTH = 21